baseURL = "/"
languageCode = "en-us"
title = "Open Science Group"
theme = "reveal-hugo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[author]
name = "David Bovill"

[params.reveal_hugo]
history = true
