baseURL = "/"
languageCode = "en-us"
title = "Open Science Group"
theme = "."
themesDir = "../"

[author]
name = "David Bovill"

[params.reveal_hugo]
history = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
