baseURL = "/"
languageCode = "en-us"
title = "Open Science Group"
disableKinds = ["sitemap", "RSS"]
theme = "."
themesDir = "../"

[author]
name = "Josh Dzielak"

[params.reveal_hugo]
history = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
